-- Lugar
INSERT INTO LUGAR values (1, 'Afganistán','PAÍS', 'ASIA', 'AFN');
INSERT INTO LUGAR values (2, 'Albania','PAÍS', 'EUROPA', 'ALL');
INSERT INTO LUGAR values (3, 'Argelia','PAÍS', 'ÁFRICA', 'DZD');
INSERT INTO LUGAR values (4, 'Andorra','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR values (5, 'Angola','PAÍS', 'ÁFRICA', 'AOA');
INSERT INTO LUGAR values (6, 'Azerbaiyán','PAÍS', 'ASIA', 'AZM');
INSERT INTO LUGAR values (7, 'Argentina','PAÍS', 'AMÉRICA', 'ARS');
INSERT INTO LUGAR values (8, 'Australia','PAÍS', 'OCEANÍA', 'AUD');
INSERT INTO LUGAR values (9, 'Austria','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR values (10, 'Bahamas','PAÍS', 'AMÉRICA', 'BSD');
INSERT INTO LUGAR values (11, 'Bahréin','PAÍS', 'ASIA', 'BHD');
INSERT INTO LUGAR values (12, 'Bangladesh','PAÍS', 'ASIA', 'BDT');
INSERT INTO LUGAR values (13, 'Armenia','PAÍS', 'ASIA', 'AMD');
INSERT INTO LUGAR values (14, 'Barbados','PAÍS', 'AMÉRICA', 'BBD');
INSERT INTO LUGAR values (15, 'Bélgica','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR values (16, 'Bermudas','PAÍS', 'AMÉRICA', 'BMD');
INSERT INTO LUGAR values (17, 'Bhután','PAÍS', 'ASIA', 'BTN');
INSERT INTO LUGAR values (18, 'Bolivia','PAÍS', 'AMÉRICA', 'BOB');
INSERT INTO LUGAR values (19, 'Bosnia y Herzegovina','PAÍS', 'EUROPA', 'BAM');
INSERT INTO LUGAR values (20, 'Botsuana','PAÍS', 'ÁFRICA', 'BWP');
INSERT INTO LUGAR values (21, 'Brasil','PAÍS', 'AMÉRICA', 'BRL');
INSERT INTO LUGAR values (22, 'Belice','PAÍS', 'AMÉRICA', 'BZD');
INSERT INTO LUGAR values (23, 'Islas Salomón','PAÍS', 'OCEANÍA', 'SBD');
INSERT INTO LUGAR values (24, 'Brunéi','PAÍS', 'ASIA', 'BND');
INSERT INTO LUGAR values (25, 'Bulgaria','PAÍS', 'EUROPA', 'BGN');
INSERT INTO LUGAR values (26, 'Myanmar','PAÍS', 'ASIA', 'MMK');
INSERT INTO LUGAR values (27, 'Burundi','PAÍS', 'ÁFRICA', 'BIF');
INSERT INTO LUGAR values (28, 'Bielorrusia','PAÍS', 'EUROPA', 'BYR');
INSERT INTO LUGAR values (29, 'Camboya','PAÍS', 'ASIA', 'KHR');
INSERT INTO LUGAR values (30, 'Canadá','PAÍS', 'AMÉRICA', 'CAD');
INSERT INTO LUGAR values (31, 'Cabo Verde','PAÍS', 'ÁFRICA', 'CVE');
INSERT INTO LUGAR values (32, 'Islas Caimán','PAÍS', 'AMÉRICA', 'KYD');
INSERT INTO LUGAR values (33, 'Sri Lanka','PAÍS', 'ASIA', 'LKR');
INSERT INTO LUGAR values (34, 'Chile','PAÍS', 'AMÉRICA', 'CLP');
INSERT INTO LUGAR values (35, 'China','PAÍS', 'ASIA', 'CNY');
INSERT INTO LUGAR values (36, 'Taiwán','PAÍS', 'ASIA', 'TWD');
INSERT INTO LUGAR values (37, 'Colombia','PAÍS', 'AMÉRICA', 'COP');
INSERT INTO LUGAR values (38, 'Comoras','PAÍS', 'ÁFRICA', 'KMF');
INSERT INTO LUGAR values (39, 'República Democrática del Congo','PAÍS', 'ÁFRICA', 'CDF');
INSERT INTO LUGAR values (40, 'Costa Rica','PAÍS', 'AMÉRICA', 'CRC');
INSERT INTO LUGAR values (41, 'Croacia','PAÍS', 'EUROPA', 'HRK');
INSERT INTO LUGAR values (42, 'Cuba','PAÍS', 'AMÉRICA', 'CUP');
INSERT INTO LUGAR values (43, 'Chipre','PAÍS', 'EUROPA', 'CYP');
INSERT INTO LUGAR values (44, 'República Checa','PAÍS', 'EUROPA', 'CZK');
INSERT INTO LUGAR values (45, 'Dinamarca','PAÍS', 'EUROPA', 'DKK');
INSERT INTO LUGAR values (46, 'República Dominicana','PAÍS', 'AMÉRICA', 'DOP');
INSERT INTO LUGAR values (47, 'El Salvador','PAÍS', 'AMÉRICA', 'SVC');
INSERT INTO LUGAR values (48, 'Etiopía','PAÍS', 'ÁFRICA', 'ETB');
INSERT INTO LUGAR values (49, 'Eritrea','PAÍS', 'ÁFRICA', 'ERN');
INSERT INTO LUGAR values (50, 'Estonia','PAÍS', 'EUROPA', 'EEK');
INSERT INTO LUGAR values (51, 'Islas Malvinas','PAÍS', 'AMÉRICA', 'FKP');
INSERT INTO LUGAR values (52, 'Fiyi','PAÍS', 'OCEANÍA', 'FJD');
INSERT INTO LUGAR values (53, 'Finlandia','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR values (54, 'Francia','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR values (55, 'Yibuti','PAÍS', 'ÁFRICA', 'DJF');
INSERT INTO LUGAR values (56, 'Georgia','PAÍS', 'EUROPA', 'GEL');
INSERT INTO LUGAR values (57, 'Gambia','PAÍS', 'ÁFRICA', 'GMD');
INSERT INTO LUGAR values (58, 'Alemania','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR values (59, 'Ghana','PAÍS', 'ÁFRICA', 'GHC');
INSERT INTO LUGAR values (60, 'Gibraltar','PAÍS', 'EUROPA', 'GIP');
INSERT INTO LUGAR values (61, 'Grecia','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR values (62, 'Guatemala','PAÍS', 'AMÉRICA', 'GTQ');
INSERT INTO LUGAR values (63, 'Guinea','PAÍS', 'ÁFRICA', 'GNF');
INSERT INTO LUGAR values (64, 'Guyana','PAÍS', 'AMÉRICA', 'GYD');
INSERT INTO LUGAR values (65, 'Haití','PAÍS', 'AMÉRICA', 'HTG');
INSERT INTO LUGAR values (66, 'Honduras','PAÍS', 'AMÉRICA', 'HNL');
INSERT INTO LUGAR values (67, 'Hong Kong','PAÍS', 'ASIA', 'HKD');
INSERT INTO LUGAR values (68, 'Hungría','PAÍS', 'EUROPA', 'HUF');
INSERT INTO LUGAR values (69, 'Islandia','PAÍS', 'EUROPA', 'ISK');
INSERT INTO LUGAR values (70, 'India','PAÍS', 'ASIA', 'INR');
INSERT INTO LUGAR values (71, 'Indonesia','PAÍS', 'ASIA', 'IDR');
INSERT INTO LUGAR values (72, 'Irán','PAÍS', 'ASIA', 'IRR');
INSERT INTO LUGAR values (73, 'Iraq','PAÍS', 'ASIA', 'IQD');
INSERT INTO LUGAR values (74, 'Irlanda','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR values (75, 'Israel','PAÍS', 'ASIA', 'ILS');
INSERT INTO LUGAR values (76, 'Italia','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR values (77, 'Jamaica','PAÍS', 'AMÉRICA', 'JMD');
INSERT INTO LUGAR values (78, 'Japón','PAÍS', 'ASIA', 'JPY');
INSERT INTO LUGAR values (79, 'Kazajstán','PAÍS', 'ASIA', 'KZT');
INSERT INTO LUGAR values (80, 'Jordania','PAÍS', 'ASIA', 'JOD');
INSERT INTO LUGAR values (81, 'Kenia','PAÍS', 'ÁFRICA', 'KES');
INSERT INTO LUGAR values (82, 'Corea del Norte','PAÍS', 'ASIA', 'KPW');
INSERT INTO LUGAR values (83, 'Corea del Sur','PAÍS', 'ASIA', 'KRW');
INSERT INTO LUGAR values (84, 'Kuwait','PAÍS', 'ASIA', 'KWD');
INSERT INTO LUGAR values (85, 'Kirguistán','PAÍS', 'ASIA', 'KGS');
INSERT INTO LUGAR values (86, 'Laos','PAÍS', 'ASIA', 'LAK');
INSERT INTO LUGAR values (87, 'Líbano','PAÍS', 'ASIA', 'LBP');
INSERT INTO LUGAR values (88, 'Lesotho','PAÍS', 'ÁFRICA', 'LSL');
INSERT INTO LUGAR values (89, 'Letonia','PAÍS', 'EUROPA', 'LVL');
INSERT INTO LUGAR values (90, 'Liberia','PAÍS', 'ÁFRICA', 'LRD');
INSERT INTO LUGAR values (91, 'Libia','PAÍS', 'ÁFRICA', 'LYD');
INSERT INTO LUGAR values (92, 'Lituania','PAÍS', 'EUROPA', 'LTL');
INSERT INTO LUGAR values (93, 'Luxemburgo','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR values (94, 'Macao','PAÍS', 'ASIA', 'MOP');
INSERT INTO LUGAR values (95, 'Madagascar','PAÍS', 'ÁFRICA', 'MGA');
INSERT INTO LUGAR values (96, 'Malaui','PAÍS', 'ÁFRICA', 'MWK');
INSERT INTO LUGAR values (97, 'MalASIA','PAÍS', 'ASIA', 'MYR');
INSERT INTO LUGAR values (98, 'Maldivas','PAÍS', 'ASIA', 'MVR');
INSERT INTO LUGAR values (99, 'Malta','PAÍS', 'EUROPA', 'MTL');
INSERT INTO LUGAR values (100, 'Mauritania','PAÍS', 'ÁFRICA', 'MRO');
INSERT INTO LUGAR values (101, 'Mauricio','PAÍS', 'ÁFRICA', 'MUR');
INSERT INTO LUGAR values (102, 'México','PAÍS', 'AMÉRICA', 'MXN');
INSERT INTO LUGAR values (103, 'Mongolia','PAÍS', 'ASIA', 'MNT');
INSERT INTO LUGAR values (104, 'Moldavia','PAÍS', 'EUROPA', 'MDL');
INSERT INTO LUGAR values (105, 'Marruecos','PAÍS', 'ÁFRICA', 'MAD');
INSERT INTO LUGAR values (106, 'Mozambique','PAÍS', 'ÁFRICA', 'MZM');
INSERT INTO LUGAR values (107, 'Omán','PAÍS', 'ASIA', 'OMR');
INSERT INTO LUGAR values (108, 'Namibia','PAÍS', 'ÁFRICA', 'NAD');
INSERT INTO LUGAR values (109, 'Nepal','PAÍS', 'ASIA', 'NPR');
INSERT INTO LUGAR values (110, 'Países Bajos','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR values (111, 'Antillas Holandesas','PAÍS', 'AMÉRICA', 'ANG');
INSERT INTO LUGAR values (112, 'Aruba','PAÍS', 'AMÉRICA', 'AWG');
INSERT INTO LUGAR values (113, 'Vanuatu','PAÍS', 'OCEANÍA', 'VUV');
INSERT INTO LUGAR values (114, 'Nueva Zelanda','PAÍS', 'OCEANÍA', 'NZD');
INSERT INTO LUGAR values (115, 'Nicaragua','PAÍS', 'AMÉRICA', 'NIO');
INSERT INTO LUGAR values (116, 'Nigeria','PAÍS', 'ÁFRICA', 'NGN');
INSERT INTO LUGAR values (117, 'Noruega','PAÍS', 'EUROPA', 'NOK');
INSERT INTO LUGAR values (118, 'Pakistán','PAÍS', 'ASIA', 'PKR');
INSERT INTO LUGAR values (119, 'Panamá','PAÍS', 'AMÉRICA', 'PAB');
INSERT INTO LUGAR values (120, 'Papúa Nueva Guinea','PAÍS', 'OCEANÍA', 'PGK');
INSERT INTO LUGAR values (121, 'Paraguay','PAÍS', 'AMÉRICA', 'PYG');
INSERT INTO LUGAR values (122, 'Perú','PAÍS', 'AMÉRICA', 'PEN');
INSERT INTO LUGAR values (123, 'Filipinas','PAÍS', 'ASIA', 'PHP');
INSERT INTO LUGAR values (124, 'Polonia','PAÍS', 'EUROPA', 'PLN');
INSERT INTO LUGAR values (125, 'Portugal','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR values (126, 'Qatar','PAÍS', 'ASIA', 'QAR');
INSERT INTO LUGAR values (127, 'Rumania','PAÍS', 'EUROPA', 'RON');
INSERT INTO LUGAR values (128, 'Rusia','PAÍS', 'ASIA', 'RUB');
INSERT INTO LUGAR values (129, 'Ruanda','PAÍS', 'ÁFRICA', 'RWF');
INSERT INTO LUGAR values (130, 'Santa Helena','PAÍS', 'ÁFRICA', 'SHP');
INSERT INTO LUGAR values (131, 'Santo Tomé y Príncipe','PAÍS', 'ÁFRICA', 'STD');
INSERT INTO LUGAR values (132, 'Arabia Saudí','PAÍS', 'ASIA', 'SAR');
INSERT INTO LUGAR values (133, 'Seychelles','PAÍS', 'ÁFRICA', 'SCR');
INSERT INTO LUGAR values (134, 'Sierra Leona','PAÍS', 'ÁFRICA', 'SLL');
INSERT INTO LUGAR values (135, 'Singapur','PAÍS', 'ASIA', 'SGD');
INSERT INTO LUGAR values (136, 'Eslovaquia','PAÍS', 'EUROPA', 'SKK');
INSERT INTO LUGAR values (137, 'Vietnam','PAÍS', 'ASIA', 'VND');
INSERT INTO LUGAR values (138, 'Somalia','PAÍS', 'ÁFRICA', 'SOS');
INSERT INTO LUGAR values (139, 'SudÁFRICA','PAÍS', 'ÁFRICA', 'ZAR');
INSERT INTO LUGAR values (140, 'Zimbabue','PAÍS', 'ÁFRICA', 'ZWL');
INSERT INTO LUGAR values (141, 'España','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR values (142, 'Sudán','PAÍS', 'ÁFRICA', 'SDD');
INSERT INTO LUGAR values (143, 'Surinam','PAÍS', 'AMÉRICA', 'SRD');
INSERT INTO LUGAR values (144, 'Suazilandia','PAÍS', 'ÁFRICA', 'SZL');
INSERT INTO LUGAR values (145, 'Suecia','PAÍS', 'EUROPA', 'SEK');
INSERT INTO LUGAR values (146, 'Suiza','PAÍS', 'EUROPA', 'CHF');
INSERT INTO LUGAR values (147, 'Siria','PAÍS', 'ASIA', 'SYP');
INSERT INTO LUGAR values (148, 'Tayikistán','PAÍS', 'ASIA', 'TJS');
INSERT INTO LUGAR values (149, 'Tailandia','PAÍS', 'ASIA', 'THB');
INSERT INTO LUGAR values (150, 'Tonga','PAÍS', 'OCEANÍA', 'TOP');
INSERT INTO LUGAR values (151, 'Trinidad y Tobago','PAÍS', 'AMÉRICA', 'TTD');
INSERT INTO LUGAR values (152, 'Emiratos Árabes Unidos','PAÍS', 'ASIA', 'AED');
INSERT INTO LUGAR values (153, 'Túnez','PAÍS', 'ÁFRICA', 'TND');
INSERT INTO LUGAR values (154, 'Turquía','PAÍS', 'ASIA', 'TRY');
INSERT INTO LUGAR values (155, 'Turkmenistán','PAÍS', 'ASIA', 'TMM');
INSERT INTO LUGAR values (156, 'Uganda','PAÍS', 'ÁFRICA', 'UGX');
INSERT INTO LUGAR values (157, 'Ucrania','PAÍS', 'EUROPA', 'UAH');
INSERT INTO LUGAR values (158, 'Macedonia','PAÍS', 'EUROPA', 'MKD');
INSERT INTO LUGAR values (159, 'Egipto','PAÍS', 'ÁFRICA', 'EGP');
INSERT INTO LUGAR values (160, 'Reino Unido','PAÍS', 'EUROPA', 'GBP');
INSERT INTO LUGAR values (161, 'Tanzania','PAÍS', 'ÁFRICA', 'TZS');
INSERT INTO LUGAR values (162, 'Estados Unidos','PAÍS', 'AMÉRICA', 'USD');
INSERT INTO LUGAR values (163, 'Uruguay','PAÍS', 'AMÉRICA', 'UYU');
INSERT INTO LUGAR values (164, 'Uzbekistán','PAÍS', 'ASIA', 'UZS');
INSERT INTO LUGAR values (165, 'Venezuela','PAÍS', 'AMÉRICA', 'VEB');
INSERT INTO LUGAR values (166, 'Samoa','PAÍS', 'OCEANÍA', 'WST');
INSERT INTO LUGAR values (167, 'Yemen','PAÍS', 'ASIA', 'YER');
INSERT INTO LUGAR values (168, 'Zambia','PAÍS', 'ÁFRICA', 'ZMK');



