-- Lugar
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Afganistán','PAÍS', 'ASIA', 'AFN');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Albania','PAÍS', 'EUROPA', 'ALL');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Argelia','PAÍS', 'ÁFRICA', 'DZD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Andorra','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Angola','PAÍS', 'ÁFRICA', 'AOA');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Azerbaiyán','PAÍS', 'ASIA', 'AZM');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Argentina','PAÍS', 'AMÉRICA', 'ARS');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Australia','PAÍS', 'OCEANÍA', 'AUD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Austria','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Bahamas','PAÍS', 'AMÉRICA', 'BSD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Bahréin','PAÍS', 'ASIA', 'BHD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Bangladesh','PAÍS', 'ASIA', 'BDT');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Armenia','PAÍS', 'ASIA', 'AMD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Barbados','PAÍS', 'AMÉRICA', 'BBD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Bélgica','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Bermudas','PAÍS', 'AMÉRICA', 'BMD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Bhután','PAÍS', 'ASIA', 'BTN');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Bolivia','PAÍS', 'AMÉRICA', 'BOB');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Bosnia y Herzegovina','PAÍS', 'EUROPA', 'BAM');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Botsuana','PAÍS', 'ÁFRICA', 'BWP');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Brasil','PAÍS', 'AMÉRICA', 'BRL');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Belice','PAÍS', 'AMÉRICA', 'BZD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Islas Salomón','PAÍS', 'OCEANÍA', 'SBD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Brunéi','PAÍS', 'ASIA', 'BND');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Bulgaria','PAÍS', 'EUROPA', 'BGN');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Myanmar','PAÍS', 'ASIA', 'MMK');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Burundi','PAÍS', 'ÁFRICA', 'BIF');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Bielorrusia','PAÍS', 'EUROPA', 'BYR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Camboya','PAÍS', 'ASIA', 'KHR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Canadá','PAÍS', 'AMÉRICA', 'CAD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Cabo Verde','PAÍS', 'ÁFRICA', 'CVE');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Islas Caimán','PAÍS', 'AMÉRICA', 'KYD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Sri Lanka','PAÍS', 'ASIA', 'LKR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Chile','PAÍS', 'AMÉRICA', 'CLP');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'China','PAÍS', 'ASIA', 'CNY');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Taiwán','PAÍS', 'ASIA', 'TWD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Colombia','PAÍS', 'AMÉRICA', 'COP');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Comoras','PAÍS', 'ÁFRICA', 'KMF');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'República Democrática del Congo','PAÍS', 'ÁFRICA', 'CDF');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Costa Rica','PAÍS', 'AMÉRICA', 'CRC');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Croacia','PAÍS', 'EUROPA', 'HRK');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Cuba','PAÍS', 'AMÉRICA', 'CUP');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Chipre','PAÍS', 'EUROPA', 'CYP');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'República Checa','PAÍS', 'EUROPA', 'CZK');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Dinamarca','PAÍS', 'EUROPA', 'DKK');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'República Dominicana','PAÍS', 'AMÉRICA', 'DOP');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'El Salvador','PAÍS', 'AMÉRICA', 'SVC');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Etiopía','PAÍS', 'ÁFRICA', 'ETB');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Eritrea','PAÍS', 'ÁFRICA', 'ERN');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Estonia','PAÍS', 'EUROPA', 'EEK');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Islas Malvinas','PAÍS', 'AMÉRICA', 'FKP');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Fiyi','PAÍS', 'OCEANÍA', 'FJD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Finlandia','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Francia','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Yibuti','PAÍS', 'ÁFRICA', 'DJF');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Georgia','PAÍS', 'EUROPA', 'GEL');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Gambia','PAÍS', 'ÁFRICA', 'GMD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Alemania','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Ghana','PAÍS', 'ÁFRICA', 'GHC');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Gibraltar','PAÍS', 'EUROPA', 'GIP');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Grecia','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Guatemala','PAÍS', 'AMÉRICA', 'GTQ');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Guinea','PAÍS', 'ÁFRICA', 'GNF');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Guyana','PAÍS', 'AMÉRICA', 'GYD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Haití','PAÍS', 'AMÉRICA', 'HTG');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Honduras','PAÍS', 'AMÉRICA', 'HNL');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Hong Kong','PAÍS', 'ASIA', 'HKD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Hungría','PAÍS', 'EUROPA', 'HUF');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Islandia','PAÍS', 'EUROPA', 'ISK');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'India','PAÍS', 'ASIA', 'INR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Indonesia','PAÍS', 'ASIA', 'IDR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Irán','PAÍS', 'ASIA', 'IRR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Iraq','PAÍS', 'ASIA', 'IQD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Irlanda','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Israel','PAÍS', 'ASIA', 'ILS');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Italia','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Jamaica','PAÍS', 'AMÉRICA', 'JMD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Japón','PAÍS', 'ASIA', 'JPY');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Kazajstán','PAÍS', 'ASIA', 'KZT');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Jordania','PAÍS', 'ASIA', 'JOD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Kenia','PAÍS', 'ÁFRICA', 'KES');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Corea del Norte','PAÍS', 'ASIA', 'KPW');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Corea del Sur','PAÍS', 'ASIA', 'KRW');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Kuwait','PAÍS', 'ASIA', 'KWD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Kirguistán','PAÍS', 'ASIA', 'KGS');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Laos','PAÍS', 'ASIA', 'LAK');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Líbano','PAÍS', 'ASIA', 'LBP');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Lesotho','PAÍS', 'ÁFRICA', 'LSL');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Letonia','PAÍS', 'EUROPA', 'LVL');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Liberia','PAÍS', 'ÁFRICA', 'LRD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Libia','PAÍS', 'ÁFRICA', 'LYD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Lituania','PAÍS', 'EUROPA', 'LTL');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Luxemburgo','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Macao','PAÍS', 'ASIA', 'MOP');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Madagascar','PAÍS', 'ÁFRICA', 'MGA');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Malaui','PAÍS', 'ÁFRICA', 'MWK');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'MalASIA','PAÍS', 'ASIA', 'MYR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Maldivas','PAÍS', 'ASIA', 'MVR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Malta','PAÍS', 'EUROPA', 'MTL');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Mauritania','PAÍS', 'ÁFRICA', 'MRO');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Mauricio','PAÍS', 'ÁFRICA', 'MUR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'México','PAÍS', 'AMÉRICA', 'MXN');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Mongolia','PAÍS', 'ASIA', 'MNT');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Moldavia','PAÍS', 'EUROPA', 'MDL');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Marruecos','PAÍS', 'ÁFRICA', 'MAD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Mozambique','PAÍS', 'ÁFRICA', 'MZM');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Omán','PAÍS', 'ASIA', 'OMR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Namibia','PAÍS', 'ÁFRICA', 'NAD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Nepal','PAÍS', 'ASIA', 'NPR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Países Bajos','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Antillas Holandesas','PAÍS', 'AMÉRICA', 'ANG');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Aruba','PAÍS', 'AMÉRICA', 'AWG');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Vanuatu','PAÍS', 'OCEANÍA', 'VUV');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Nueva Zelanda','PAÍS', 'OCEANÍA', 'NZD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Nicaragua','PAÍS', 'AMÉRICA', 'NIO');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Nigeria','PAÍS', 'ÁFRICA', 'NGN');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Noruega','PAÍS', 'EUROPA', 'NOK');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Pakistán','PAÍS', 'ASIA', 'PKR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Panamá','PAÍS', 'AMÉRICA', 'PAB');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Papúa Nueva Guinea','PAÍS', 'OCEANÍA', 'PGK');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Paraguay','PAÍS', 'AMÉRICA', 'PYG');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Perú','PAÍS', 'AMÉRICA', 'PEN');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Filipinas','PAÍS', 'ASIA', 'PHP');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Polonia','PAÍS', 'EUROPA', 'PLN');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Portugal','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Qatar','PAÍS', 'ASIA', 'QAR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Rumania','PAÍS', 'EUROPA', 'RON');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Rusia','PAÍS', 'ASIA', 'RUB');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Ruanda','PAÍS', 'ÁFRICA', 'RWF');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Santa Helena','PAÍS', 'ÁFRICA', 'SHP');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Santo Tomé y Príncipe','PAÍS', 'ÁFRICA', 'STD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Arabia Saudí','PAÍS', 'ASIA', 'SAR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Seychelles','PAÍS', 'ÁFRICA', 'SCR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Sierra Leona','PAÍS', 'ÁFRICA', 'SLL');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Singapur','PAÍS', 'ASIA', 'SGD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Eslovaquia','PAÍS', 'EUROPA', 'SKK');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Vietnam','PAÍS', 'ASIA', 'VND');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Somalia','PAÍS', 'ÁFRICA', 'SOS');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'SudÁFRICA','PAÍS', 'ÁFRICA', 'ZAR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Zimbabue','PAÍS', 'ÁFRICA', 'ZWL');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'España','PAÍS', 'EUROPA', 'EUR');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Sudán','PAÍS', 'ÁFRICA', 'SDD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Surinam','PAÍS', 'AMÉRICA', 'SRD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Suazilandia','PAÍS', 'ÁFRICA', 'SZL');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Suecia','PAÍS', 'EUROPA', 'SEK');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Suiza','PAÍS', 'EUROPA', 'CHF');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Siria','PAÍS', 'ASIA', 'SYP');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Tayikistán','PAÍS', 'ASIA', 'TJS');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Tailandia','PAÍS', 'ASIA', 'THB');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Tonga','PAÍS', 'OCEANÍA', 'TOP');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Trinidad y Tobago','PAÍS', 'AMÉRICA', 'TTD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Emiratos Árabes Unidos','PAÍS', 'ASIA', 'AED');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Túnez','PAÍS', 'ÁFRICA', 'TND');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Turquía','PAÍS', 'ASIA', 'TRY');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Turkmenistán','PAÍS', 'ASIA', 'TMM');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Uganda','PAÍS', 'ÁFRICA', 'UGX');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Ucrania','PAÍS', 'EUROPA', 'UAH');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Macedonia','PAÍS', 'EUROPA', 'MKD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Egipto','PAÍS', 'ÁFRICA', 'EGP');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Reino Unido','PAÍS', 'EUROPA', 'GBP');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Tanzania','PAÍS', 'ÁFRICA', 'TZS');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Estados Unidos','PAÍS', 'AMÉRICA', 'USD');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Uruguay','PAÍS', 'AMÉRICA', 'UYU');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Uzbekistán','PAÍS', 'ASIA', 'UZS');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Venezuela','PAÍS', 'AMÉRICA', 'VEB');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Samoa','PAÍS', 'OCEANÍA', 'WST');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Yemen','PAÍS', 'ASIA', 'YER');
INSERT INTO LUGAR (Lug_Nombre,Lug_Tipo,Lug_Continente,Lug_Moneda) values ( 'Zambia','PAÍS', 'ÁFRICA', 'ZMK');



insert into PAIS (pai_nombre,pai_continente) values ('Argentina','AMÉRICA');
insert into PAIS (pai_nombre,pai_continente) values ('Italia','EUROPA');



